version: '3'
services:
  postgres:
    image: postgres:15
    container_name: orders_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=avengers
      - POSTGRES_DB=ordersdb
    volumes:
      - ./postgres:/var/lib/postgresql/data